services:
  - type: web
    name: sports_challenge_tracker_app
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: PORT
        value: 3000